# Generated by Django 5.0.3 on 2024-04-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='movies', to='user.rating'),
        ),
    ]
