# Generated by Django 5.0.3 on 2024-04-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_movie_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='comment',
        ),
    ]
